// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefrAhVqh9Yhh7fq__beQGUASY6a5Yen4',
    appId: '1:277126759608:web:bf753042e81b0bc73a204d',
    messagingSenderId: '277126759608',
    projectId: 'startec-a4468',
    authDomain: 'startec-a4468.firebaseapp.com',
    storageBucket: 'startec-a4468.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgR04QTNlls0kv3x6iD2sZRnyYyhkzrM',
    appId: '1:277126759608:android:b76d9c32b7fa35963a204d',
    messagingSenderId: '277126759608',
    projectId: 'startec-a4468',
    storageBucket: 'startec-a4468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuk9uRRmcuRYsmCs9XBxEnSdWbZymLUAw',
    appId: '1:277126759608:ios:395f6b996f799a4e3a204d',
    messagingSenderId: '277126759608',
    projectId: 'startec-a4468',
    storageBucket: 'startec-a4468.firebasestorage.app',
    iosBundleId: 'com.example.startec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuk9uRRmcuRYsmCs9XBxEnSdWbZymLUAw',
    appId: '1:277126759608:ios:395f6b996f799a4e3a204d',
    messagingSenderId: '277126759608',
    projectId: 'startec-a4468',
    storageBucket: 'startec-a4468.firebasestorage.app',
    iosBundleId: 'com.example.startec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDefrAhVqh9Yhh7fq__beQGUASY6a5Yen4',
    appId: '1:277126759608:web:fb601ba6b26f47783a204d',
    messagingSenderId: '277126759608',
    projectId: 'startec-a4468',
    authDomain: 'startec-a4468.firebaseapp.com',
    storageBucket: 'startec-a4468.firebasestorage.app',
  );
}
